export { BigTitle } from "./BigTitle";
export { Hero } from "./Hero";
export { HomePage } from "./HomePage";
export { InnerPageWrapper } from "./InnerPageWrapper";
export { Line } from "./Line";
export { Projects } from "./Projects";
export { SectionTitle } from "./SectionTitle";
export { Skills } from "./Skills";
export { SubTitle } from "./SubTitle";
